enabled: true

env:
  SET_VERSION_OVERRIDE: 5.0.1-$GIT_BRANCH-SNAPSHOT

buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2-single-module

provides:
  - name: easy-random
    version: 5.0.1-$GIT_BRANCH-SNAPSHOT
