enabled: true

env:
  SET_VERSION_OVERRIDE: 5.0.0-$GIT_BRANCH-SNAPSHOT

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2

provides:
  name: easy-random
  version: 5.0.0-$GIT_BRANCH-SNAPSHOT
