enabled: true

provides:
  - name: easy-random-randomizers
    version: 5.0.1-$GIT_BRANCH-SNAPSHOT

depends:
  - easy-random-core

env:
  SET_VERSION_OVERRIDE: 5.0.1-$GIT_BRANCH-SNAPSHOT

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2
